name: nytimes
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bootstrap:
    path: packages/bootstrap
  core:
    path: packages/core
  design:
    path: packages/design
  equatable: ^2.0.3
  extended_image: ^6.0.2+1
  flutter_bloc: ^8.0.1
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  go_router: ^3.0.7
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  network:
    path: packages/network
  url_launcher: ^6.0.20
  timeago: ^3.2.2
  provider: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.9
  bloc_test: ^9.0.3
  flutter_lints: ^1.0.0
  http_mock_adapter: ^0.3.2


flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
